mybatis:
  mapper-locations: mappers/**/*.xml


file:
  directory: D:/2024-02/download/greengram_ver2

const:
  default-page-size: 20

spring:
  # DB setting
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # ?? ?? (?? ??)
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver2 # ?? ?? (?? ??)
    username: root
    password: green502
  application:
    name: GreenGramVer2
  servlet:
    multipart:
      max-file-size: 15MB



springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache: WARN
    ch.qos.logback: ERROR
    org.springframework.boot.logging: ERROR
    org.springframework.boot.autoconfigure: WARN